### ISSUE TITLE
Corrupt Package

### ISSUE THREAD

**Issue by olaayeko** [Marco-Congedo/FourierAnalysis.jl#48]
Installing this package has made Plots and DifferentialEquations no longer work in my Julia. This error does not resolve after installing/reinstalling Julia

**Comment by Marco-Congedo** [comment]
It would be useful to know with what version of Julia this happened to you, how did you solve it and if this is reproducible elsewhere. I have no hint for the moment being as neither Plots.jl nor DifferentialEquations.jl are a dependency of FourierAnalysis.jl.

**Comment by felixcremer** [comment]
This package has RecipesBase 0.7 in its compat list and is therefore not compatible with Plots 1.0. I tried to set the compat entry for RecipesBase to 1 but the plots are looking broken and I am not sure enough how they should look like to fix this.

**Comment by Marco-Congedo** [comment]
Hello,

  the package has been built with a more ancient version of Plots. I have run the following example extracted from the example section in the doc of the `spectra` function:
```
using FourierAnalysis

function generateSomeData(sr::Int, t::Int; noise::Real=1.)
    # four sinusoids of length t samples and sr sampling rate
    # peak amplitude: 0.7, 0.6, 0.5, 0.4
    # frequency:        5,   7,  13,  27
    # phase:            0, π/4, π/2,   π
    v1=sinusoidal(0.7, 5,  sr, t, 0)
    v2=sinusoidal(0.6, 7,  sr, t, π/4)
    v3=sinusoidal(0.5, 13, sr, t, π/2)
    v4=sinusoidal(0.4, 27, sr, t, π)
    return hcat(v1, v2, v3, v4) + (randn(t, 4)*noise)
end

sr, wl, t = 128, 512, 8192
X=generateSomeData(sr, t)
# multivariate data matrix 8192x4

# compute spectra
S=spectra(X, sr, wl)

# check the spectrum of first series
S.y[:, 1]

# gather some plot attributes to get nice plots
using Plots, Plots.Measures
spectraArgs=(fmax = 32,
             left_margin = 2mm,
             bottom_margin = 2mm,
             xtickfont = font(11, "Times"),
             ytickfont = font(11, "Times"))
plot(S; spectraArgs...)
```

This is how it looks like:
![image](https://user-images.githubusercontent.com/47817916/108097161-137dc100-7082-11eb-9af3-1b162f876dac.png)

Running the following example from the `TFanalyticsignal` function

```
using FourierAnalysis

# generate some data
sr, t, bandwidth=128, 512, 2
h=taper(harris4, t)
x1=sinusoidal(10, 8, sr, t, 0)
x2=sinusoidal(10, 19, sr, t, 0)
x=Vector((x1+x2).*h.y+randn(t))
y1=sinusoidal(10, 6, sr, t, 0)
y2=sinusoidal(10, 16, sr, t, 0)
y=Vector((y1+y2).*h.y+randn(t))
plot([x, y])


# TFAnalyticSignal object for x (method (1))
Y = TFanalyticsignal(x, sr, sr*4; fmax=32)

# gather first useful attributes for the plot
using Plots, Plots.Measures
tfArgs=(right_margin = 2mm,
        top_margin = 2mm,
        xtickfont = font(10, "Times"),
        ytickfont = font(10, "Times"))

# Plot the real part of the analytic signal
heatmap(tfAxes(Y)..., real(Y.y);
        c=:pu_or, tfArgs...)
```

plots the series data and then

![image](https://user-images.githubusercontent.com/47817916/108098045-32c91e00-7083-11eb-8739-a2461eee537b.png)

**Comment by Marco-Congedo** [comment]
Working fine

**Comment by Marco-Congedo** [comment]
Hello, I updated all dependencies to the latest versions. 
v1.2.0 of FourierAnalysis.jl is currently in the hand of the bot for registration and will be available soon.
