### ISSUE TITLE
Unable to add this package in Julia 1.5.2 / Windows 10

### ISSUE THREAD

**Issue by rafael-guerra-www** [Marco-Congedo/FourierAnalysis.jl#49]
I am unable to add this package in Julia 1.5.2 / Windows 10.
Fyi, please find error log herein:
```
ERROR: Unsatisfiable requirements detected for package RecipesPipeline [01d81517]:
 RecipesPipeline [01d81517] log:
 ├─possible versions are: 0.1.0-0.1.13 or uninstalled
 ├─restricted to versions 0.1.6-0.1 by StatsPlots [f3b207a7], leaving only versions 0.1.6-0.1.13
 │ └─StatsPlots [f3b207a7] log:
 │   ├─possible versions are: 0.14.13 or uninstalled
 │   └─StatsPlots [f3b207a7] is fixed to version 0.14.13
 └─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: uninstalled — no versions left
   └─RecipesBase [3cdcf5f2] log:
     ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0] or uninstalled
     ├─restricted to versions [0.6-0.8, 1] by StatsPlots [f3b207a7], leaving only versions [0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0]
     │ └─StatsPlots [f3b207a7] log: see above
     └─restricted by compatibility requirements with FourierAnalysis [e7e9c730] to versions: 0.7.0
       └─FourierAnalysis [e7e9c730] log:
         ├─possible versions are: [1.0.0-1.0.1, 1.1.0] or uninstalled
         └─restricted to versions * by an explicit requirement, leaving only versions [1.0.0-1.0.1, 1.1.0]
```

Thanks for any recommendations to succeed.

**Comment by Marco-Congedo** [comment]
Hi, I am running smoothly the FourierAnalysis.jl package in Julia v1.5.1.
The log here above does not seem complete.
Also, can you run it on Julia v 1.5.1?

**Comment by rafael-guerra-www** [comment]
Sorry for my inexperience. I have many packages installed in home project and it became messy to handle the version constraints and dependency problems. I have activated (pkg> activate .) a new project and managed to install FourierAnalysis in Julia 1.5.2, getting the pretty welcome greeting:
⭐  Welcome to the FourierAnalysis.jl package ⭐
Thanks for your message.

**Comment by Marco-Congedo** [comment]
Good to hear that Rafael. Enjoy FourierAnalysis.jl!

**Comment by rafael-guerra-www** [comment]
Thanks Marco. With help of your package I have managed to generate the time-frequency plot attached, where the input is a measured non-linear chirp type of signal with harmonics, the horizontal scale is time in seconds and the vertical is frequency in Hertz. The amplitude is plotted in dB (20*log).
The Hilbert/analytical signal method seems to miss the lower amplitude harmonics in the input signal. I have read that this is a known limitation and that the Hilbert-Huang transform (HHT) would be able to capture also the non-linear weaker harmonics. I would like to ask if you have any plan to add the HHT technique to FourierAnalysis.jl?

![FourierAnalyis_tf_heatmap](https://user-images.githubusercontent.com/20739393/95655427-e20f4a80-0b0f-11eb-9e3b-9293e767f1ff.png)

**Comment by Marco-Congedo** [comment]
Hi Rafael,

  nice plot 👍 

I do not have plans to add the Hilbert-Huang transform, however you can do it and it is pretty straightforward.
I guess all you need to do is to add another '_analyticsignal!' function in the hilbert.jl unit,
which computes the transform you want. Then, you would just add an argument to all
functions computing the analytic signal to choose in between the Hilbert transform
and the Hilbert-Huang transform. 

Cheers,
Marco
