### ISSUE TITLE
README demo not working

### ISSUE THREAD

**Issue by henry2004y** [Marco-Congedo/FourierAnalysis.jl#66]
Hi,

Thanks for building and sharing this package!

I tried to run the example in README.md, but something is not working:

- `t` in `randn(t*16, 4)` not defined
- After I replaced `t` with `wl`
```julia
julia> heatmap(A)
ERROR: Cannot convert TFAmplitude to series data for plotting
```

**Comment by Marco-Congedo** [comment]
Hello,

   thanks for spotting this.
My fault, `A` is a TFAmplitude type, so its data field `.y` must be passed to `heatmap`. I corrected the README.
All the best,
