### ISSUE TITLE
Question about coherence

### ISSUE THREAD

**Issue by henry2004y** [Marco-Congedo/FourierAnalysis.jl#68]
Hi,

Forgive me about my ignorance in Fourier analysis. I have some questions about computing coherence and cross-spectrum and whether or not this package provides such functionalities.

I want to perform some analysis similar to the [wavelet coherence](https://se.mathworks.com/help/wavelet/ref/wcoherence.html) as demonstrated in the link to MATLAB's documentation. Simply speaking, given two time-series `x` and `y`, I want to compute the correlation coefficients in the time-frequency domain. However, it seems to me that the word "coherence" and "cross-spectral" in Fourier analysis refer to cross-correlations, which I am not sure if that's what I'm looking for.

Do you know if it's possible to perform my desired analysis with this package?

**Comment by Marco-Congedo** [comment]
Hi, you are looking for Coherence, which is a standardized version of Cross-Spectra. Sure you can do it with FourierAnalysis.jl, furthermore, you can do for any number of time series to get a coherence matrix.

**Comment by henry2004y** [comment]
Great! Can you kindly provide me with a basic example to start with? Better
with a heatmap like plot included.

**Comment by henry2004y** [comment]
Great! Can you kindly provide me with a basic example to start with? Better
with a heatmap like plot included.

```julia
using FourierAnalysis, LinearAlgebra, Plots

function generateSomeData(sr::Int, t::Int; noise::Real=1.)
    # 2 sinusoids of length t samples and sr sampling rate
    # peak amplitude: 0.7, 0.5
    # frequency:        5, 13
    # phase:            0, π/2
    v1 = sinusoidal(0.7, 5,  sr, t, 0)
    v2 = sinusoidal(0.5, 13, sr, t, π/2)
    return hcat(v1, v2) + (randn(t, 2)*noise)
end

sr, wl, t = 128, 512, 8192

X = generateSomeData(sr, t) # multivariate data matrix 8192x4

# cross-spectra using default harris4 tapering window
S = crossSpectra(X, sr, wl)

# Only classical coherence
C = coherence(S)

# What should I do next to get a time-frequency heatmap plot of coherence?
```

**Comment by Marco-Congedo** [comment]
The `coherence` function i referred to only produces a coherence matrix, as this is a method in the frequency domain, not in the time-frequency domain. For the `coherence` function in the time-frequency domain run [this example](https://github.com/Marco-Congedo/FourierAnalysis.jl/blob/master/examples/example_timefrequencybi.jl). Note that in order to run the example you have to download on your computer also the following files: EEGdata1.txt, EEGdata2.txt and IOtxt.jl (and put them all in the same  directory).

**Comment by Marco-Congedo** [comment]
PS: in the time-frequency domain the function is only bivariate, meaning that you can compute the coherence among two time-series at the time only.

**Comment by henry2004y** [comment]
Thanks for the guidance! I feel like I'm getting closer, but this [example_timefrequencybi.jl](https://github.com/Marco-Congedo/FourierAnalysis.jl/blob/master/examples/example_timefrequencybi.jl) and the [doc of time-frequency domain](https://marco-congedo.github.io/FourierAnalysis.jl/dev/coherence/#coherence-estimates) still confuse me (most likely because I am not familar with the basics).

In the example file, 

```julia
X1 = readEEG(S[1]) # 2048×19 Matrix{Float64}
X2 = readEEG(S[2]) # 2048×19 Matrix{Float64}
```

and then

```julia
Pz = 15
Fz = 5
𝐱₁ = [X1[:, Pz], X2[:, Pz]] # get the two times-series at electrode Pz
𝐱₂ = [X1[:, Fz], X2[:, Fz]] # get the two times-series at electrode Fz
```

This is my first confusing point: to construct `𝐘₁=TFanalyticsignal(𝐱₁, sr, wl, bandwidth; fmax=32, nonlinear=false)` later, two vectors of length 2048 are used. Same goes for `𝐘₂`, And then

```julia
Coh=FourierAnalysis.coherence(𝐘₁, 𝐘₂, (8, 12), (1, 512); mode=mean)
Coh=FourierAnalysis.coherence(𝐘₁, 𝐘₂, (8, 12), (1, 512); mode=extract)
```

gives the coherence between `𝐘₁` and `𝐘₂`. How is this analogous to my goal of obtaining the correlation coefficients between two real vector of equal length, e.g. `x = rand(2048)` and `y = rand(2048)`? What I have in mind is something like

```julia
x = rand(2048)
y = rand(2048)
Coh = FourierAnalysis.coherence(x, y, args...)
```

which is similar to the `wcoh = wcoherence(x,y)` function in the MATLAB wavelet toolbox but performed with Fourier transform underneath.

**Comment by Marco-Congedo** [comment]
read the [documentation of the coherence function](https://marco-congedo.github.io/FourierAnalysis.jl/dev/coherence/#FourierAnalysis.coherence)
It is a pretty complex one and you can do a lot of things with.

**Comment by Marco-Congedo** [comment]
And please note that coherence, like all other univariate and bivariate measures in the time-frequency domain, are computed as averages of several realizations. See [this paper](https://hal.archives-ouvertes.fr/hal-01868538v2/document) for clarifications.

**Comment by henry2004y** [comment]
Now I have a better understanding of the nomenclatures after going through your paper and other related materials. So, to answer my own question,

```julia
Pz = 15
Fz = 5
x1 = [X1[:, Pz], X2[:, Pz]] # get the two times-series at electrode Pz
x2 = [X1[:, Fz], X2[:, Fz]] # get the two times-series at electrode Fz
```

here `x1` and `x2` are just two signals, each consisting of two trials/realizations. The raw data contains 19 sensors, and the two file are output from two independent realizations.

The output I want to get shall come out of this

```julia
Coh=FourierAnalysis.coherence(Y1, Y2, (8, 12), (1, 512); mode=extract, allkinds=true)
```

method. Given the fact that my data, unlike the EEG data, only have 1 realization per sensor/channel, in principle it should be analogous to

```julia
x1 = [ X1[:, Pz] ]
x2 = [ X1[:, Fz] ]

Y1 = TFanalyticsignal(x1, sr, wl, bandwidth; fmax=32, nonlinear=false)
Y2 = TFanalyticsignal(x2, sr, wl, bandwidth; fmax=32, nonlinear=false)

coh = FourierAnalysis.coherence(Y1, Y2, (8, 12), (1, 512); mode=extract, allkinds=true)
```

There are 5 kinds of coherence, among which the total, instantaneous, and lagged are all ones, and the real and imaginary ones add up to the total. My intuition tells me that the real coherence shall related to the amplitude, and the imaginary coherence shall related to the phase. So, to plot something similar to the [wavelet coherence analysis in MATLAB](https://se.mathworks.com/help/wavelet/ref/wcoherence.html), the real coherence would be the color and the imaginary coherence would be converted into the arrows for showing the phase information.
